// Generated by `pnpm supabase:types`. Regenerate after every migration.
// Placeholder until first generation.

export interface Database {
    public: {
        Tables: Record<string, never>;
        Views: Record<string, never>;
        Functions: Record<string, never>;
        Enums: Record<string, never>;
    };
}
