-- ============================================================================
-- 20260929000002_prepurchase_ledger_seq.sql
-- Deterministic ordering for prepurchase_ledger.
--
-- now() is fixed for the whole transaction, so several ledger rows written in
-- one transaction (a repricing run, say) share an identical created_at. id is
-- a random uuid, so nothing recovered insertion order and a reader ordering by
-- created_at alone could show any of the tied rows as the latest — displaying
-- a running balance that disagrees with the account.
--
-- seq is monotonic per insert and breaks the tie. Readers order by
-- (created_at, seq); created_at still drives the visible chronology.
-- ============================================================================

alter table public.prepurchase_ledger
    add column if not exists seq bigint generated by default as identity;

comment on column public.prepurchase_ledger.seq is
    'Monotonic insertion counter. Tie-breaks rows sharing a created_at (now() is per-transaction). Order by (created_at, seq), never created_at alone.';

-- Existing rows are assigned identity values in physical order, which is
-- arbitrary within a created_at tie. Re-derive them so ordering is stable.
with ordered as (
    select id, row_number() over (order by created_at, seq) as rn
    from public.prepurchase_ledger
)
update public.prepurchase_ledger l
set    seq = ordered.rn
from   ordered
where  ordered.id = l.id;

select setval(
    pg_get_serial_sequence('public.prepurchase_ledger', 'seq'),
    coalesce((select max(seq) from public.prepurchase_ledger), 1)
);

create index if not exists prepurchase_ledger_account_seq_idx
    on public.prepurchase_ledger (account_id, created_at desc, seq desc);
