-- ============================================================================
-- 20260929000003_prepurchase_price_history.sql
-- Audit trail for pre-purchase deal rates.
--
-- prepurchase_prices stored current values only — no updated_at, no history.
-- Deal rates are negotiated per sale and get renegotiated, so a rate change
-- left no trace and the original agreement was unrecoverable from the schema.
-- Today's WESTBROOK rebase is only on record because it ran from a checked-in
-- script; an edit made through the panel would have vanished.
--
-- Written by trigger, not by the application, so every path is covered —
-- server action, SQL editor, psql, a future admin UI.
-- ============================================================================

create table if not exists public.prepurchase_price_history (
    id                     uuid primary key default gen_random_uuid(),
    seq                    bigint generated by default as identity,
    account_id             uuid not null references public.prepurchase_accounts(id) on delete cascade,
    product_code           text not null,
    operation              text not null check (operation in ('baseline', 'insert', 'update', 'delete')),
    old_sale_per_cm2_cents bigint,
    new_sale_per_cm2_cents bigint,
    old_cost_per_cm2_cents bigint,
    new_cost_per_cm2_cents bigint,
    -- auth.uid() when an end user made the change. Most portal writes run
    -- through the service role, where it is null — the row still records what
    -- changed and when. Deliberately NOT a foreign key: a missing profile row
    -- must never be able to fail a price update.
    changed_by             uuid,
    note                   text,
    changed_at             timestamptz not null default now()
);

-- (changed_at, seq) for the same reason the ledger needed it: now() is fixed
-- per transaction, so a multi-row rate change shares one timestamp.
create index if not exists prepurchase_price_history_account_idx
    on public.prepurchase_price_history (account_id, changed_at desc, seq desc);

comment on table public.prepurchase_price_history is
    'Append-only audit of prepurchase_prices. Written by trigger; no update or delete policy exists, so history cannot be rewritten from the app.';

-- ---------------------------------------------------------------------------
-- Trigger
-- ---------------------------------------------------------------------------
create or replace function public.fn_log_prepurchase_price_change()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
    if tg_op = 'INSERT' then
        insert into public.prepurchase_price_history (
            account_id, product_code, operation,
            new_sale_per_cm2_cents, new_cost_per_cm2_cents, changed_by)
        values (new.account_id, new.product_code, 'insert',
            new.sale_per_cm2_cents, new.cost_per_cm2_cents, auth.uid());
        return new;

    elsif tg_op = 'UPDATE' then
        -- Only record a real change; a no-op write shouldn't pad the history.
        if new.sale_per_cm2_cents is distinct from old.sale_per_cm2_cents
           or new.cost_per_cm2_cents is distinct from old.cost_per_cm2_cents then
            insert into public.prepurchase_price_history (
                account_id, product_code, operation,
                old_sale_per_cm2_cents, new_sale_per_cm2_cents,
                old_cost_per_cm2_cents, new_cost_per_cm2_cents, changed_by)
            values (new.account_id, new.product_code, 'update',
                old.sale_per_cm2_cents, new.sale_per_cm2_cents,
                old.cost_per_cm2_cents, new.cost_per_cm2_cents, auth.uid());
        end if;
        return new;

    else
        insert into public.prepurchase_price_history (
            account_id, product_code, operation,
            old_sale_per_cm2_cents, old_cost_per_cm2_cents, changed_by)
        values (old.account_id, old.product_code, 'delete',
            old.sale_per_cm2_cents, old.cost_per_cm2_cents, auth.uid());
        return old;
    end if;
end $$;

drop trigger if exists trg_prepurchase_price_history on public.prepurchase_prices;
create trigger trg_prepurchase_price_history
    after insert or update or delete on public.prepurchase_prices
    for each row execute function public.fn_log_prepurchase_price_change();

-- ---------------------------------------------------------------------------
-- RLS — admins read; nobody writes except the trigger (security definer).
-- ---------------------------------------------------------------------------
alter table public.prepurchase_price_history enable row level security;

drop policy if exists pp_price_history_admin_read on public.prepurchase_price_history;
create policy pp_price_history_admin_read on public.prepurchase_price_history
    for select to authenticated
    using (public.is_admin());

-- ---------------------------------------------------------------------------
-- Baseline: one row per existing rate, so history has a floor to read back to.
-- These are the values as of this migration, not the original agreement —
-- anything changed before today is genuinely unrecoverable.
-- ---------------------------------------------------------------------------
insert into public.prepurchase_price_history (
    account_id, product_code, operation,
    new_sale_per_cm2_cents, new_cost_per_cm2_cents, note)
select pp.account_id, pp.product_code, 'baseline',
       pp.sale_per_cm2_cents, pp.cost_per_cm2_cents,
       'Baseline captured when price history was introduced'
from   public.prepurchase_prices pp
where  not exists (
    select 1 from public.prepurchase_price_history h
    where h.account_id = pp.account_id and h.product_code = pp.product_code
);
